### ISSUE TITLE
hello 曹博，请问cctr有开源计划吗？

### ISSUE THREAD

**Issue by dcspsy** [ChengtaiCao/ChengtaiCao.github.io#1]
如题，论文场景比较符合我们业务问题，想关注下时间表。
CCTR: Calibrating Trajectory Prediction for Uncertainty-Aware Motion Planning in A Autonomous DrivingChengtai Cao, Xinhong Chen, Jianping Wang, Qun Song, Rui TaTan,Yung-Hui Li

**Comment by ChengtaiCao** [comment]
您好，由于本项目还在专利流程中，因此后续才会公布源代码，不过可以提供一些细节来帮助您的业务。

1. CCTR用于在轨迹预测和路径规划模块之间，并且期望轨迹预测模型输出分布且路径规划可以利用分布中的方差信息。
2. 可以使用最简单的 temperature_scaling 做初步探索是否有效参考：https://github.com/gpleiss/temperature_scaling 或者 https://arxiv.org/pdf/2210.06391.pdf
3. 后续再加入 Kinematics、Social、Spatiotemporal 等信息看是否有进一步提升

后续开源之后会回复此问题以通知您。

**Comment by dcspsy** [comment]
> 您好，由于本项目还在专利流程中，因此后续才会公布源代码，不过可以提供一些细节来帮助您的业务。
> 
> 1. CCTR用于在轨迹预测和路径规划模块之间，并且期望轨迹预测模型输出分布且路径规划可以利用分布中的方差信息。
> 2. 可以使用最简单的 temperature_scaling 做初步探索是否有效参考：https://github.com/gpleiss/temperature_scaling 或者 https://arxiv.org/pdf/2210.06391.pdf
> 3. 后续再加入 Kinematics、Social、Spatiotemporal 等信息看是否有进一步提升
> 
> 后续开源之后会回复此问题以通知您。

感谢！
